# Meu primeiro Markdown
## Python

In [ ]:
nome = "joaquin"
idade = 34
valor_em_carteira = 345.99
vip = True

print(nome)

In [1]:
def soma_dois_valores(primeiro,segundo):
    resultado = primeiro + segundo 
    return resultado

valor_1 = 10
valor_2 = 20

soma = soma_dois_valores(valor_1,valor_2)

print(soma)

30

In [6]:
lista_clientes = ["joaquina","jose","joão","Maria"]
lista_produtos = ["Maça","Banana","Chocolate"]

lista_clientes.append("Roberta")
print(lista_clientes[4])

Roberta

In [8]:
lista_vendas = []

venda = ("banana",4,8.50)

lista_vendas.append(venda)
print(lista_vendas)

[('banana', 4, 8.5)]

In [ ]:
cliente_1 = {
     "nome":"joaquin",
     "idade":34,
     "vip" : True,
     "carteira":345.99
}

cliente_2 = { 
     "nome":"roberta", #chave e valor pode modificar o valor ma a chave nao 
     "idade":24,
     "vip" : False,
     "carteira":1245.99
}
cliente_2["idade"] = 25

lista_clientes = [cliente_1,cliente_2]
print(lista_clientes)
print(cliente_1["carteira"])

In [4]:
import math

print(math.pow(3,4))
print(math.tan(2))

81.0
-2.185039863261519

In [25]:
import numpy as np 

numpy_array = np.arange(0,1_000_000 + 1 , dtype = "int64")
#Tempo de execuçao : 0.008s
## memoria utilizada:7.5 MiB

# Tipos e Acesso aos Elementos de um Array

In [ ]:
# criando um array
import numpy as np

arr = np.array([1,2,3,4,5])
print(f"elementos:{arr},Tipo dos elementos:{arr.dtype} , tamanho do array:{arr.shape}")

##Criando uma matrix 
matrix = np.arange(1.,10).reshape((3,3))
print(matrix)
print (f"tipos dos elementos:{matrix.dtype},Dimensoes da matriz:{matrix.shape}")

## Acessando a 2 linha :
linha = matrix[1]
print(linha)

## Acessando a 1 coluna:
coluna = matrix[:,1]
print(coluna)

In [29]:
import numpy as np

a = np.array([1.0,2.0,3.0])
b = 2.0
resultado = a * b
print(resultado)

[2. 4. 6.]

# Multiplicacao utilizando apenas listas em Python

In [30]:
import numpy as np

A = np.array([[1, 2], [3,4], [5,6]])
B = np.array([[1], [2]])
print(A)
print(B)


#Multiplicação das Matrizes

D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]]
[[ 5]
 [11]
 [17]]

In [26]:
import numpy as np

N = 500

A = np.arange(N*N , dtype = "int64").reshape(N,N)#pega os dados de um array e reorganiza o formato (shape) dele, sem mudar os valores nem a quantidade total de elementos — só muda como eles estão "arrumados" em linhas e colunas (ou mais dimensões).
B = A * 2

C = A @ B #@multiplica as matrizes

print(C)

[[   41541750000    41541999500    41542249000 ...    41665751500
     41666001000    41666250500]
 [  103916750000   103917499500   103918249000 ...   104289251500
    104290001000   104290750500]
 [  166291750000   166292999500   166294249000 ...   166912751500
    166914001000   166915250500]
 ...
 [31041916750000 31042165499500 31042414249000 ... 31165545251500
  31165794001000 31166042750500]
 [31104291750000 31104540999500 31104790249000 ... 31228168751500
  31228418001000 31228667250500]
 [31166666750000 31166916499500 31167166249000 ... 31290792251500
  31291042001000 31291291750500]]

# Pandas:Series e DataFrames

# Series

In [27]:
import pandas as pd
cidades = [
    "Sao paulo (SP)",
    "Rio de Janeiro(RJ)",
    "Brasilia(DF)",
    "Fortaleza(CE)",
    "Salvador(BA)",
    "Belo horizonte",
    "Manaus(AM)",
    "Curitiba(PR)", 
]

populacoes = [
    12,
    6.5,
    3,
    2.4,
    2.4,
    2.3,
    2,
    1.7
   
]

cidades_series = pd.Series(cidades)
print(cidades_series)

populacoes_series = pd.Series(populacoes)
print(populacoes_series)

print(cidades_series[3])
print(cidades_series[3:5])
print(populacoes_series.max())#numero mais alto
print(populacoes_series.mean())#media

0        Sao paulo (SP)
1    Rio de Janeiro(RJ)
2          Brasilia(DF)
3         Fortaleza(CE)
4          Salvador(BA)
5        Belo horizonte
6            Manaus(AM)
7          Curitiba(PR)
dtype: str
0    12.0
1     6.5
2     3.0
3     2.4
4     2.4
5     2.3
6     2.0
7     1.7
dtype: float64
Fortaleza(CE)
3    Fortaleza(CE)
4     Salvador(BA)
dtype: str
12.0
4.0375

# DataFrames

In [34]:
import pandas as pd

cidades_populosas = pd.DataFrame({"cidade": cidades_series,"populacao em milhoes":populacoes_series})
print(cidades_populosas)

(cidades_populosas.info())
(cidades_populosas["cidade"])#pega so a coluna cidade
cidades_populosas.iloc[3]#seleciona dados de um DataFrame por indices de posicao
cidades_populosas.iloc[3:5]#o ultimo nunca pega fica do 3 ate 4
cidades_populosas.head()#exibe as primeiras 5 linhas do DataFrame 
cidades_populosas.tail()#exibe as 5 ultimas linhas do DataFrame
cidades_populosas["populacao em milhoes".mean()]#tira a media da coluna de populacoes em milhoes

               cidade  populacao em milhoes
0      Sao paulo (SP)                  12.0
1  Rio de Janeiro(RJ)                   6.5
2        Brasilia(DF)                   3.0
3       Fortaleza(CE)                   2.4
4        Salvador(BA)                   2.4
5      Belo horizonte                   2.3
6          Manaus(AM)                   2.0
7        Curitiba(PR)                   1.7
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cidade                8 non-null      str
 1   populacao em milhoes  8 non-null      float64
dtypes: float64(1), str(1)
memory usage: 260.0 bytes

AttributeError: 'str' object has no attribute 'mean'

# Adicionando Colunas

In [44]:
area_urbana = [
    "914",
    "640",
    "590",
    "253",
    "196",
    "274",
    "277",
    "336",
]
print(area_urbana)
cidades_populosas["area urbana em km2"] = area_urbana
cidades_populosas

['914', '640', '590', '253', '196', '274', '277', '336']

,cidade,populacao em milhoes,area urbana em km,populacao,area urbana em km2
0,Sao paulo (SP),12.0,914,12000000.0,914
1,Rio de Janeiro(RJ),6.5,640,6500000.0,640
2,Brasilia(DF),3.0,590,3000000.0,590
3,Fortaleza(CE),2.4,253,2400000.0,253
4,Salvador(BA),2.4,196,2400000.0,196
5,Belo horizonte,2.3,274,2300000.0,274
6,Manaus(AM),2.0,277,2000000.0,277
7,Curitiba(PR),1.7,336,1700000.0,336

# Aplicando Funções

In [47]:
cidades_populosas["populacao"] = cidades_populosas["populacao em milhoes"]*1_000_000
(cidades_populosas)

print(cidades_populosas.info())
cidades_populosas["area urbana em km2"] = cidades_populosas["area urbana em km2"].astype(int)#ASTYPE converte o tipo de dados de uma ou mais colunas de um DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cidade                8 non-null      str
 1   populacao em milhoes  8 non-null      float64
 2   area urbana em km     8 non-null      str
 3   populacao             8 non-null      float64
 4   area urbana em km2    8 non-null      int64
dtypes: float64(2), int64(1), str(2)
memory usage: 452.0 bytes
None

# Combinando Dados de colunas

In [51]:
cidades_populosas["habitantes por km2"] = cidades_populosas["populacao"] / cidades_populosas["area urbana em km2"]
cidades_populosas

,cidade,populacao em milhoes,area urbana em km,populacao,area urbana em km2,habitantes por km2
0,Sao paulo (SP),12.0,914,12000000.0,914,13129.102845
1,Rio de Janeiro(RJ),6.5,640,6500000.0,640,10156.250000
2,Brasilia(DF),3.0,590,3000000.0,590,5084.745763
3,Fortaleza(CE),2.4,253,2400000.0,253,9486.166008
4,Salvador(BA),2.4,196,2400000.0,196,12244.897959
5,Belo horizonte,2.3,274,2300000.0,274,8394.160584
6,Manaus(AM),2.0,277,2000000.0,277,7220.216606
7,Curitiba(PR),1.7,336,1700000.0,336,5059.523810

# Teste

In [ ]:
def classificar_populacao(pop):#criei uma funcao
    if pop > 10_000_000:
        return "Megacidade"
    else:
        return "Cidade grande"

cidades_populosas["categoria"] = cidades_populosas["populacao"].apply(classificar_populacao)